##### Menu
menu:
  Home: /
  Archives: /archives
  About: /about
## ---

#### Widgets
widgets:
- recentPosts
- category
- tag
- tagcloud
- archive
- links


## provide six widgets:category,tag,recentPosts,archive,tagcloud,links.
## modify links in `/layout/_widget/links.jade`.

#### RSS
rss: /atom.xml

#### author information
github: ##eg: 'git_name' will be 'http://github.com/git_name'
weibo:  ##eg: 'weibo_name' will be 'http://weibo.com/weibo_name'
facebook: ##eg: 'facebook_name' will be 'http://facebook.com/facebook_name'

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/myLogo.png       ## `.svg` and `.png` are recommended,please put image into the theme folder `/pacman/source/img`.
favicon: img/myFavicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/pacman/source/img`.     


#### Font
ShowCustomFont: true  
## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/pacman/source/css`.

#### Toc
toc:
  article: true   ## show contents in article.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Comment
duoshuo: 
  enable: false  ## duoshuo.com
  short_name: ## duoshuo short name.

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.

#### Analytics
google_analytics:
  enable: false
  id:   ## e.g. UA-1766729-8 your google analytics ID.
  site: ## e.g. yangjian.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN

baidu_analytics: false

